// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptimusBillingProject.Models;

namespace OptimusBillingProject.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OptimusBillingProject.Entity.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastBilledDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalBilledAmount")
                        .HasColumnType("real");

                    b.Property<float>("TotalBilledHours")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastBilledDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TotalBilledAmount = 200f,
                            TotalBilledHours = 200f
                        },
                        new
                        {
                            Id = 2,
                            LastBilledDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TotalBilledAmount = 250f,
                            TotalBilledHours = 250f
                        },
                        new
                        {
                            Id = 3,
                            LastBilledDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TotalBilledAmount = 300f,
                            TotalBilledHours = 300f
                        },
                        new
                        {
                            Id = 4,
                            LastBilledDate = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TotalBilledAmount = 400f,
                            TotalBilledHours = 400f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
